const fs = require('fs');

function updateBudgetData(filePath) {
    console.log(`Loading ${filePath}...`);
    let data;
    try {
        const fileContent = fs.readFileSync(filePath, 'utf-8');
        data = JSON.parse(fileContent);
    } catch (e) {
        console.error(`Error loading file: ${e}`);
        return;
    }

    const itinerary = data.itinerary || {};
    let updatedCount = 0;

    console.log("Checking itinerary days...");
    for (const [dayId, dayData] of Object.entries(itinerary)) {
        if (!dayData.accommodation || typeof dayData.accommodation !== 'object') {
            console.log(`Updating ${dayId}: Adding default accommodation object.`);
            dayData.accommodation = {
                name: "",
                address: "",
                link: ""
            };
            updatedCount++;
        } else {
            const acc = dayData.accommodation;
            if (acc.name === undefined) acc.name = "";
            if (acc.address === undefined) acc.address = "";
            if (acc.link === undefined) acc.link = "";
        }

        if (dayData.expenses && dayData.expenses.accommodation !== undefined) {
            console.log(`Fixing ${dayId}: Removing legacy 'accommodation' expense field.`);
            delete dayData.expenses.accommodation;
            updatedCount++;
        }
    }

    if (updatedCount > 0) {
        console.log(`Saving modifications... (${updatedCount} days updated)`);
        try {
            fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
            console.log("Success!");
        } catch (e) {
            console.error(`Error saving file: ${e}`);
        }
    } else {
        console.log("No changes needed in JSON structure.");
    }

    try {
        console.log("Syncing data.js with latest budget_data.json content...");
        const jsContent = fs.readFileSync('js/data.js', 'utf-8');
        const jsonStr = JSON.stringify(data, null, 2);
        const fallbackCode = `\n// --- FALLBACK DATA (Auto-generated by update_json.py) ---\nwindow.fallbackData = ${jsonStr};\n`;

        const marker = "// --- FALLBACK DATA";
        let newJsContent;
        if (jsContent.includes(marker)) {
            const parts = jsContent.split(marker);
            newJsContent = parts[0] + fallbackCode;
        } else {
            newJsContent = jsContent + "\n" + fallbackCode;
        }

        fs.writeFileSync('js/data.js', newJsContent, 'utf-8');
        console.log("Successfully synced data.js!");
    } catch (e) {
        console.error(`Error updating data.js: ${e}`);
    }
}

updateBudgetData('js/budget_data.json');
