import json
import os

def update_budget_data(file_path):
    print(f"Loading {file_path}...")
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error loading file: {e}")
        return

    itinerary = data.get('itinerary', {})
    updated_count = 0

    print("Checking itinerary days...")
    for day_id, day_data in itinerary.items():
        # Check if accommodation object exists
        if 'accommodation' not in day_data or not isinstance(day_data['accommodation'], dict):
            print(f"Updating {day_id}: Adding default accommodation object.")
            # Preserve existing simple value if it was just a number (backwards compat attempt, though unlikely needed based on file view)
            # based on file view it was just a number in expenses, but this is a top level object now.
            # In budget_data.json currently: "accommodation": 0 exists in fixedCosts, but inside itinerary J1..J19 it doesn't exist at all.
            # wait, I saw "accommodation": 165 inside expenses. 
            # I want to add day_data['accommodation'] = { ... }
            
            day_data['accommodation'] = {
                "name": "",
                "address": "",
                "link": ""
            }
            updated_count += 1
        else:
             # Ensure all keys exist even if object exists
            acc = day_data['accommodation']
            if "name" not in acc: acc["name"] = ""
            if "address" not in acc: acc["address"] = ""
            if "link" not in acc: acc["link"] = ""
            if "name" not in acc: acc["name"] = ""
            if "address" not in acc: acc["address"] = ""
            if "link" not in acc: acc["link"] = ""
            # print(f"{day_id} already has accommodation object.")

        # BUG FIX: Remove legacy 'accommodation' from expenses to prevent double counting
        if 'expenses' in day_data and 'accommodation' in day_data['expenses']:
            print(f"Fixing {day_id}: Removing legacy 'accommodation' expense field.")
            day_data['expenses'].pop('accommodation')
            updated_count += 1

    if updated_count > 0:
        print(f"Saving modifications... ({updated_count} days updated)")
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            print("Success!")
        except Exception as e:
            print(f"Error saving file: {e}")
    else:
        print("No changes needed in JSON structure.")

    # ALWAYS update data.js with the latest JSON content (even if no structure changes)
    # This ensures strict sync between budget_data.json and window.fallbackData
    try:
        print("Syncing data.js with latest budget_data.json content...")
        
        # Read the current data.js
        with open('js/data.js', 'r', encoding='utf-8') as f:
            js_content = f.read()

        # Prepare the fallback string
        json_str = json.dumps(data, indent=2, ensure_ascii=False)
        fallback_code = f"\n// --- FALLBACK DATA (Auto-generated by update_json.py) ---\nwindow.fallbackData = {json_str};\n"

        # Check if we already have the fallback section
        marker = "// --- FALLBACK DATA"
        if marker in js_content:
            # Replace existing
            parts = js_content.split(marker)
            new_js_content = parts[0] + fallback_code
        else:
            # Append if missing
            new_js_content = js_content + "\n" + fallback_code

        with open('js/data.js', 'w', encoding='utf-8') as f:
            f.write(new_js_content)
        
        print("Successfully synced data.js!")

    except Exception as e:
        print(f"Error updating data.js: {e}")

if __name__ == "__main__":
    file_path = "js/budget_data.json"
    if os.path.exists(file_path):
        update_budget_data(file_path)
    else:
        print(f"File not found: {file_path}")
